spring:
  datasource:
    url: ${DB_URL}            # ej: jdbc:postgresql://host:5432/orders
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
